name: 'Build'

on:
  push:
    branches:
      - main

jobs:
  upload-artifacts:
    needs: [build-tweet-lambda-package, build-youtube-lambda-package]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: ./create_youtube_lambda_package.sh
      shell: bash

    - uses: actions/checkout@v3
    - name: Install dependencies
      run: ./create_tweet_lambda_package.sh
      shell: bash

    - uses: actions/upload-artifact@v3
    - name: Upload Build Packages
      with:
        name: lambda-builds
        path: |
         ../tweet_youtube_video.zip
         ../youtube_video_generator.zip