name: Format Code

on: 
  workflow_dispatch:

jobs:
  format-black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black
    - name: Formatting the code with black
      run: |
        black $(git ls-files 'lambdas/')

  run-pylint:
    needs: format-black
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint --rcfile=.pylintrc $(git ls-files '*.py')

  checkov:
    needs: run-pylint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform/
          framework: terraform 
          config_file: .checkov.yaml
